/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AttachmentNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var crypto = __toESM(require("crypto"));
var DEFAULT_SETTINGS = {
  inputFolder: "Attachments",
  outputFolder: "",
  autoProcess: true,
  promptForName: false,
  recursiveScan: false,
  noteTemplate: `# {{filename}}

## File Information

- **Original name:** {{originalName}}
- **MD5 Hash:** {{hash}}
- **File size:** {{size}}
- **File type:** {{extension}}
- **Created:** {{date}}

## Description

Add your notes here.

## Linked File

[[{{hash}}.{{extension}}]]`
};
var AttachmentNotePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.isProcessing = false;
  }
  // Prevent recursive processing
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "process-all-attachments",
      name: "Process all files in input folder",
      callback: () => this.processAllFiles()
    });
    this.addCommand({
      id: "process-current-attachment",
      name: "Create attachment note for current file",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && activeFile.extension !== "md") {
          if (!checking) {
            this.processSingleFile(activeFile);
          }
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension !== "md") {
          menu.addItem((item) => {
            item.setTitle("Create attachment note").setIcon("document").onClick(() => this.processSingleFile(file));
          });
        }
      })
    );
    this.addSettingTab(new AttachmentNoteSettingTab(this.app, this));
    if (this.settings.autoProcess) {
      this.registerEvent(
        this.app.vault.on("create", (file) => {
          if (this.isProcessing) return;
          if (file instanceof import_obsidian.TFile && file.extension !== "md") {
            this.checkAndProcessFile(file);
          }
        })
      );
    }
    const statusBarItem = this.addStatusBarItem();
    statusBarItem.createEl("span", {
      text: "\u{1F4CE} AttNote",
      attr: { style: "margin-right: 10px; opacity: 0.7;" }
    });
    console.log("Attachment Note Plugin loaded");
  }
  onunload() {
    console.log("Attachment Note Plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Check if a file is already processed (named as MD5 hash)
   */
  isFileAlreadyProcessed(file) {
    const fileName = file.basename;
    const md5Pattern = /^[a-f0-9]{32}$/i;
    return md5Pattern.test(fileName);
  }
  /**
   * Check if a file should be processed based on input folder settings
   */
  async checkAndProcessFile(file) {
    if (file.extension === "md") return;
    if (this.isFileAlreadyProcessed(file)) {
      console.log(`Skipping already processed file: ${file.path} (already in MD5 format)`);
      return;
    }
    const inputFolderPath = this.settings.inputFolder;
    const filePath = file.path;
    if (!inputFolderPath || inputFolderPath === "") {
      if (!filePath.includes("/")) {
        await this.processSingleFile(file);
      }
      return;
    }
    const isInInputFolder = filePath.startsWith(inputFolderPath + "/") || filePath === inputFolderPath;
    if (!isInInputFolder) return;
    if (this.settings.recursiveScan) {
      await this.processSingleFile(file);
      return;
    }
    const parentPath = file.parent ? file.parent.path : "";
    if (parentPath === inputFolderPath) {
      await this.processSingleFile(file);
    }
  }
  /**
   * Get all binary files from a folder (with optional recursion)
   */
  async getAllFilesFromFolder(folder) {
    const files = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile && child.extension !== "md") {
        if (!this.isFileAlreadyProcessed(child)) {
          files.push(child);
        } else {
          console.log(`Skipping already processed file: ${child.path} (already in MD5 format)`);
        }
      } else if (child instanceof import_obsidian.TFolder && this.settings.recursiveScan) {
        const subFiles = await this.getAllFilesFromFolder(child);
        files.push(...subFiles);
      }
    }
    return files;
  }
  /**
   * Process all files in the input folder
   */
  async processAllFiles() {
    if (this.isProcessing) {
      new import_obsidian.Notice("Already processing files. Please wait...");
      return;
    }
    this.isProcessing = true;
    try {
      const inputFolderPath = this.settings.inputFolder;
      if (!inputFolderPath || inputFolderPath === "") {
        const rootFiles = this.app.vault.getRoot().children;
        const files = rootFiles.filter(
          (f) => f instanceof import_obsidian.TFile && f.extension !== "md" && !this.isFileAlreadyProcessed(f)
        );
        if (files.length === 0) {
          new import_obsidian.Notice("No binary files found in root folder.");
          return;
        }
        new import_obsidian.Notice(`Processing ${files.length} file(s)...`);
        for (const file of files) {
          await this.processSingleFile(file);
        }
        new import_obsidian.Notice(`Processed ${files.length} file(s).`);
      } else {
        const inputFolder = this.app.vault.getAbstractFileByPath(inputFolderPath);
        if (!inputFolder || !(inputFolder instanceof import_obsidian.TFolder)) {
          new import_obsidian.Notice(`Input folder "${inputFolderPath}" does not exist.`);
          return;
        }
        const files = await this.getAllFilesFromFolder(inputFolder);
        if (files.length === 0) {
          new import_obsidian.Notice("No unprocessed binary files found in input folder.");
          return;
        }
        new import_obsidian.Notice(`Processing ${files.length} file(s)...`);
        for (const file of files) {
          await this.processSingleFile(file);
        }
        new import_obsidian.Notice(`Processed ${files.length} file(s).`);
      }
    } finally {
      this.isProcessing = false;
    }
  }
  /**
   * Convert ArrayBuffer to Buffer for crypto operations
   */
  arrayBufferToBuffer(arrayBuffer) {
    return Buffer.from(arrayBuffer);
  }
  /**
   * Process a single binary file with proper link updating
   */
  async processSingleFile(originalFile) {
    if (originalFile.extension === "md") {
      console.log("Skipping markdown file:", originalFile.name);
      return;
    }
    if (this.isFileAlreadyProcessed(originalFile)) {
      console.log(`Skipping already processed file: ${originalFile.path} (already in MD5 format)`);
      new import_obsidian.Notice(`Skipping already processed file: ${originalFile.name}`);
      return;
    }
    if (this.isProcessing) return;
    this.isProcessing = true;
    try {
      console.log("Processing file:", originalFile.path);
      const content = await this.app.vault.readBinary(originalFile);
      const buffer = this.arrayBufferToBuffer(content);
      const hash = crypto.createHash("md5");
      hash.update(buffer);
      const md5Hash = hash.digest("hex");
      const extension = originalFile.extension;
      const originalName = originalFile.basename;
      const newFileName = `${md5Hash}.${extension}`;
      const parentPath = originalFile.parent ? originalFile.parent.path : "";
      let targetFolderPath = this.settings.outputFolder;
      let targetFilePath;
      if (targetFolderPath && targetFolderPath !== "") {
        await this.ensureFolderExists(targetFolderPath);
        targetFilePath = `${targetFolderPath}/${newFileName}`;
      } else {
        targetFilePath = parentPath ? `${parentPath}/${newFileName}` : newFileName;
      }
      const existingFile = this.app.vault.getAbstractFileByPath(targetFilePath);
      if (existingFile) {
        console.log(`Target file already exists: ${targetFilePath}`);
        new import_obsidian.Notice(`File already exists: ${newFileName}. Skipping to avoid overwrite.`);
        return;
      }
      await this.app.fileManager.renameFile(originalFile, targetFilePath);
      let noteName;
      if (this.settings.promptForName) {
        const promptedName = await this.promptForNoteName(originalName);
        if (!promptedName) {
          new import_obsidian.Notice(`Note creation cancelled for: ${originalName}`);
          return;
        }
        noteName = promptedName;
      } else {
        noteName = originalName;
      }
      const fileSize = this.formatFileSize(originalFile.stat.size);
      let noteContent = this.settings.noteTemplate.replace(/{{filename}}/g, noteName).replace(/{{originalName}}/g, originalName).replace(/{{hash}}/g, md5Hash).replace(/{{extension}}/g, extension).replace(/{{size}}/g, fileSize).replace(/{{date}}/g, (/* @__PURE__ */ new Date()).toLocaleString());
      const frontmatter = `---
hash: ${md5Hash}
originalName: ${originalName}
fileType: ${extension}
fileSize: ${fileSize}
processed: ${(/* @__PURE__ */ new Date()).toISOString()}
---

`;
      noteContent = frontmatter + noteContent;
      let notePath;
      if (targetFolderPath && targetFolderPath !== "") {
        notePath = `${targetFolderPath}/${noteName}.md`;
      } else {
        notePath = parentPath ? `${parentPath}/${noteName}.md` : `${noteName}.md`;
      }
      let counter = 1;
      let finalNotePath = notePath;
      while (this.app.vault.getAbstractFileByPath(finalNotePath)) {
        const nameWithoutExt = notePath.replace(/\.md$/, "");
        finalNotePath = `${nameWithoutExt}_${counter}.md`;
        counter++;
      }
      await this.app.vault.create(finalNotePath, noteContent);
      new import_obsidian.Notice(`Created: ${noteName}.md \u2192 ${newFileName}
Links to file updated automatically!`);
    } catch (error) {
      console.error(`Failed to process ${originalFile.path}:`, error);
      new import_obsidian.Notice(`Error processing ${originalFile.name}: ${error.message}`);
    } finally {
      this.isProcessing = false;
    }
  }
  /**
   * Ensure a folder exists, create it if it doesn't
   */
  async ensureFolderExists(folderPath) {
    const normalizedPath = folderPath.replace(/^\/+|\/+$/g, "");
    if (normalizedPath === "") {
      return this.app.vault.getRoot();
    }
    let folder = this.app.vault.getAbstractFileByPath(normalizedPath);
    if (!folder) {
      await this.app.vault.createFolder(normalizedPath);
      folder = this.app.vault.getAbstractFileByPath(normalizedPath);
    }
    if (!folder || !(folder instanceof import_obsidian.TFolder)) {
      throw new Error(`Path exists but is not a folder: ${normalizedPath}`);
    }
    return folder;
  }
  /**
   * Prompt user for note name
   */
  async promptForNoteName(defaultName) {
    return new Promise((resolve) => {
      const modal = new NoteNameModal(this.app, defaultName, resolve);
      modal.open();
    });
  }
  /**
   * Format file size to human-readable format
   */
  formatFileSize(bytes) {
    if (bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB", "GB", "TB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
  }
};
var NoteNameModal = class extends import_obsidian.Modal {
  constructor(app, defaultName, onSubmit) {
    super(app);
    this.defaultName = defaultName;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter note name" });
    this.inputEl = contentEl.createEl("input", {
      type: "text",
      value: this.defaultName,
      attr: { style: "width: 100%; margin: 10px 0;" }
    });
    const buttonDiv = contentEl.createDiv({ attr: { style: "display: flex; gap: 10px; justify-content: flex-end;" } });
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => {
      this.close();
      this.onSubmit(null);
    });
    const okBtn = buttonDiv.createEl("button", { text: "OK", attr: { style: "background-color: var(--interactive-accent);" } });
    okBtn.addEventListener("click", () => {
      const value = this.inputEl.value.trim();
      this.close();
      this.onSubmit(value || this.defaultName);
    });
    this.inputEl.addEventListener("keypress", (e) => {
      if (e.key === "Enter") {
        const value = this.inputEl.value.trim();
        this.close();
        this.onSubmit(value || this.defaultName);
      }
    });
    this.inputEl.focus();
    this.inputEl.select();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AttachmentNoteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Attachment Note Settings" });
    new import_obsidian.Setting(containerEl).setName("Input folder").setDesc("Folder to watch for binary files (leave empty for vault root)").addText((text) => text.setPlaceholder("Attachments").setValue(this.plugin.settings.inputFolder).onChange(async (value) => {
      this.plugin.settings.inputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Scan subfolders recursively").setDesc("Also process binary files in subfolders of the input folder").addToggle((toggle) => toggle.setValue(this.plugin.settings.recursiveScan).onChange(async (value) => {
      this.plugin.settings.recursiveScan = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("Folder to move renamed files and notes to (leave empty to keep in source folder). All existing links will be automatically updated.").addText((text) => text.setPlaceholder("Processed").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-process files").setDesc("Automatically process files when they are added to the input folder (including subfolders if recursive scan is enabled)").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoProcess).onChange(async (value) => {
      this.plugin.settings.autoProcess = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Prompt for note name").setDesc("Show a dialog to edit the note name before creation").addToggle((toggle) => toggle.setValue(this.plugin.settings.promptForName).onChange(async (value) => {
      this.plugin.settings.promptForName = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Note template").setDesc("Template for the note content (use {{filename}}, {{originalName}}, {{hash}}, {{size}}, {{extension}}, {{date}})").addTextArea((text) => text.setPlaceholder("Enter note template...").setValue(this.plugin.settings.noteTemplate).onChange(async (value) => {
      this.plugin.settings.noteTemplate = value;
      await this.plugin.saveSettings();
    }).inputEl.setAttrs({ rows: "10", style: "width: 100%; font-family: monospace;" }));
    containerEl.createEl("hr");
    containerEl.createEl("p", {
      text: "\u{1F4CE} How it works:",
      attr: { style: "font-weight: bold; margin-top: 1em;" }
    });
    const description = containerEl.createEl("div", {
      attr: { style: "font-size: 0.9em; color: var(--text-muted); margin-top: 0.5em; line-height: 1.5;" }
    });
    const recursiveText = this.plugin.settings.recursiveScan ? "and ALL subfolders recursively" : "(without subfolders)";
    description.innerHTML = `
            \u2022 Place binary files in the input folder ${recursiveText} to auto-process them<br>
            \u2022 Or right-click any binary file and select "Create attachment note"<br>
            \u2022 Use the command palette to process all files in the input folder<br>
            \u2022 Files are renamed to &lt;MD5_HASH&gt;.&lt;ext&gt;<br>
            \u2022 Already processed files (named as MD5 hash) are automatically skipped<br>
            \u2022 ALL existing links to the file are automatically updated throughout the vault<br>
            \u2022 Notes contain YAML frontmatter with the original name and hash reference<br>
            \u2022 Markdown (.md) files are NEVER processed
        `;
  }
};
